# Generated by Django 3.1.7 on 2021-04-02 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('activity_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('folder_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='to_do_list.folder')),
            ],
        ),
    ]
